name: Generar calendario ICS

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  generar-calendario:

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:

      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependencias
        run: npm install

      - name: Generar calendario
        run: npm run calendario

      - name: Subir calendario actualizado
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Actualizar calendario ICS"
          file_pattern: calendario.ics